// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropEase.API.Data;

#nullable disable

namespace PropEase.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251017064155_AddCoreFieldsToImovel")]
    partial class AddCoreFieldsToImovel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PropEase.API.Models.Imovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Alugado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProprietarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoImovel")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProprietarioId");

                    b.ToTable("Imoveis");

                    b.HasDiscriminator<string>("TipoImovel").HasValue("Imovel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PropEase.API.Models.Proprietario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Proprietarios");
                });

            modelBuilder.Entity("PropEase.API.Models.Apartamento", b =>
                {
                    b.HasBaseType("PropEase.API.Models.Imovel");

                    b.HasDiscriminator().HasValue("Apartamento");
                });

            modelBuilder.Entity("PropEase.API.Models.Casa", b =>
                {
                    b.HasBaseType("PropEase.API.Models.Imovel");

                    b.HasDiscriminator().HasValue("Casa");
                });

            modelBuilder.Entity("PropEase.API.Models.Imovel", b =>
                {
                    b.HasOne("PropEase.API.Models.Proprietario", "Proprietario")
                        .WithMany()
                        .HasForeignKey("ProprietarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proprietario");
                });
#pragma warning restore 612, 618
        }
    }
}
